name: Auto Labeling

on:
  issues:
    types:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: '*/10 * * * *'

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ secrets.MERGETOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `automerge`'
