name: Picture Slimming

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: imgcmp
        uses: 9sako6/imgcmp@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GHTOKEN }}"
