name: Picture Slimming

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: imgcmp
        uses: 9sako6/imgcmp@master
        env:
          GITHUB_TOKEN: ${{ secrets.IMGTOKEN }}
          IGNORED_FILES: "public/*:posts/*.svg"
